headers = [
	"Tweet Id",
	"Username",
	"Timestamp",
	"#Followers",
	"#Friends",
	"#Retweets",
	"#Favorites",
	"Entities",
	"Sentiment",
	"Mentions",
	"Hashtags",
	"URLs"
	]

clean_headers = [
	'#Retweets',
	'Positive',
	'Negative',
	'Sentiment Disparity',
	'Log_#Followers',
	'Log_#Friends',
	'Log_No. of Entities',
	'Log_#Favorites',
	'Log_Time Int',
	'Mention Embedding_1',
	'Mention Embedding_2',
	'Mention Embedding_3',
	'Mention Embedding_4',
	'Mention Embedding_5',
	'Mention Embedding_6',
	'Mention Embedding_7',
	'Mention Embedding_8',
	'Mention Embedding_9',
	'Mention Embedding_10',
	'Mention Embedding_11',
	'Mention Embedding_12',
	'Mention Embedding_13',
	'Mention Embedding_14',
	'Mention Embedding_15',
	'Mention Embedding_16',
	'Mention Embedding_17',
	'Mention Embedding_18',
	'Mention Embedding_19',
	'Mention Embedding_20',
	'Mention Embedding_21',
	'Mention Embedding_22',
	'Mention Embedding_23',
	'Mention Embedding_24',
	'Mention Embedding_25',
	'Hashtag Embedding_1',
	'Hashtag Embedding_2',
	'Hashtag Embedding_3',
	'Hashtag Embedding_4',
	'Hashtag Embedding_5',
	'Hashtag Embedding_6',
	'Hashtag Embedding_7',
	'Hashtag Embedding_8',
	'Hashtag Embedding_9',
	'Hashtag Embedding_10',
	'Hashtag Embedding_11',
	'Hashtag Embedding_12',
	'Hashtag Embedding_13',
	'Hashtag Embedding_14',
	'Hashtag Embedding_15',
	'Hashtag Embedding_16',
	'Hashtag Embedding_17',
	'Hashtag Embedding_18',
	'Hashtag Embedding_19',
	'Hashtag Embedding_20',
	'Hashtag Embedding_21',
	'Hashtag Embedding_22',
	'Hashtag Embedding_23',
	'Hashtag Embedding_24',
	'Hashtag Embedding_25',
	'1-Hot_Day of Week_1',
	'1-Hot_Day of Week_2',
	'1-Hot_Day of Week_3',
	'1-Hot_Day of Week_4',
	'1-Hot_Day of Week_5',
	'1-Hot_Day of Week_6',
	'1-Hot_Day of Week_7',
	]

if __name__ == "__main__":
	print(len(clean_headers))
